# Generated by Django 5.0.2 on 2025-04-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="role",
            new_name="user_type",
        ),
    ]
