# Generated by Django 5.0.2 on 2025-05-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_email_otp_customuser_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_otp_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
