# Generated by Django 5.0.2 on 2025-04-12 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_booking_show"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="show_media/")),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_set",
                        to="user.show",
                    ),
                ),
            ],
        ),
    ]
