# Generated by Django 5.0.2 on 2025-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_showmedia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediafile",
            name="uploaded_at",
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name="ShowMedia",
        ),
    ]
