# Generated by Django 5.0.2 on 2025-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("confirmed", "Confirmed")],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
