# Generated by Django 5.0.2 on 2025-05-21 15:03

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_qrscanlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrscanlog",
            name="scanned_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="show",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
        migrations.AlterField(
            model_name="qrscanlog",
            name="district",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qrscanlog",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qrscanlog",
                to="user.show",
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="show",
            name="seat_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="show",
            name="slug",
            field=models.SlugField(blank=True, default="dummy-slug", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="show",
            name="time",
            field=models.TimeField(default=datetime.time(19, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="show",
            name="total_seats",
            field=models.IntegerField(default=0),
        ),
    ]
