# Generated by Django 5.0.2 on 2025-05-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_qrscanlog_scanned_at_show_qr_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="include_balcony",
            field=models.BooleanField(default=True),
        ),
    ]
