# Generated by Django 5.0.2 on 2025-05-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_visitorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="show_posters/"),
        ),
    ]
