# Generated by Django 5.0.2 on 2025-06-03 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_show_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.ticket",
            ),
        ),
    ]
