# Generated by Django 5.0.2 on 2025-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_booking_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRMarketingScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
